fix

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -19,18 +19,18 @@ jobs:
       with:
         python-version: 3.12
         cache: 'pip'
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-        if [ $? -ne 0 ]; then echo "Dependencies failed to install"; exit 1; fi
     - name: Create API key file
       env:
         OPENAIKEY: ${{ secrets.OPENAIKEY }}
       run: |
         echo $OPENAIKEY > .env
         cd backend
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install flake8 pytest
+        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        if [ $? -ne 0 ]; then echo "Dependencies failed to install"; exit 1; fi
     - name: Check Python version
       run: python --version | grep -q "Python 3.12" || echo "Unexpected Python version! Exiting." && exit 1
     - name: Run migrations
